name: notates-rnaseq-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - r-base=4.5.3
  - snakemake
  - multiqc
  - trim-galore
  - star=2.7.10b
  - arriba
  - rsem
  - r-readr
  - r-dplyr
  - r-msigdbr
  - bioconductor-gsva
  - bioconductor-gseabase
